#version 450 core

#define WIDTH 1280
#define HEIGHT 720

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout (binding = 0, rgba8) uniform image2D data;

void main()
{
    if(gl_GlobalInvocationID.x > WIDTH || gl_GlobalInvocationID.y > HEIGHT)
        return;
    
    
    
    imageStore(data,
               ivec2(gl_GlobalInvocationID.xy),
               vec4(0.5, 0.2, 0.35, 1.0));
}